apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-app-deployment
  labels:
    app: {{ .Values.appName }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-app
    spec:
      containers:
      - name: {{ .Values.appName }}-app-cont
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
