apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-app-svc
  labels:
    app: {{ .Values.appName }}-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.appName }}-app
