appName: factorize

replicaCount: 1
minReplicas: 1
maxReplicas: 10

image:
  repository: tbeit/factorize-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  target:
    cpu:
      averageUtilization: 65

nodeSelector: {}

tolerations: []

affinity: {}
