replicaCount: 1

image:
  repository: tbeit/factorize-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

nodeSelector: {}

tolerations: []

affinity: {}
