apiVersion: v1
kind: Service
metadata:
  name: sqrt-app-svc
  labels:
    app: sqrt-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: sqrt-app
