name: 10 Install Prometheus and Grafana (on AKS)

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Azure Resource Group Name"
        required: true
        default: "rg-taras-aks-t-eu"
      cluster_name:
        description: "AKS Cluster Name"
        required: true
        default: "aks-taras-aks-t-eu"

jobs:
  install_prometheus_grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: AZ and AKS Login and Setup
        uses: ./.github/actions/az-aks-commons
        with:
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          azure_sp_client_id: ${{ vars.AZURE_SP_CLIENT_ID }}
          resource_group: ${{ github.event.inputs.resource_group }}
          cluster_name: ${{ github.event.inputs.cluster_name }}
          azure_sp_client_secret: ${{ secrets.AZURE_SP_CLIENT_SECRET }}

      - name: Install Prometheus & Grafana
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install prometheus \
            prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace

      - name: Check Prometheus & Grafana k8s objects
        run: kubectl get all -n monitoring

      - name: Adding Workflow Summary + Prometheus & Grafana access instructions
        run: cat ./docs/apm/prometheus_grafana/post_install.md >> $GITHUB_STEP_SUMMARY
