name: 11 Install Ingress Controller (on AKS)

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Azure Resource Group Name"
        required: true
        default: "rg-taras-aks-t-eu"
      cluster_name:
        description: "AKS Cluster Name"
        required: true
        default: "aks-taras-aks-t-eu"

jobs:
  install_ingress_controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: AZ and AKS Login and Setup
        uses: ./.github/actions/az-aks-commons
        with:
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          azure_sp_client_id: ${{ vars.AZURE_SP_CLIENT_ID }}
          resource_group: ${{ github.event.inputs.resource_group }}
          cluster_name: ${{ github.event.inputs.cluster_name }}
          azure_sp_client_secret: ${{ secrets.AZURE_SP_CLIENT_SECRET }}

      - name: Enable Application Routing Add-on
        run: |
          az aks approuting enable --resource-group ${{ github.event.inputs.resource_group }} --name ${{ github.event.inputs.cluster_name }} || echo "Application routing is already enabled."

      - name: Install Ingress Controller
        run: |
          kubectl create namespace apps-test || echo "apps-test namespace already exists"
          kubectl apply -f platform/k8s/ingress_controller.yaml -n apps-test

      - name: Check Ingress Controller k8s object
        run: kubectl get ingress -n apps-test
